site_name: Getting Started with Ansible on RHEL 10
docs_dir: publishing-house/spec
nav:
- Home: index.md
- Design Spec: design.md
- Modules:
  - Module 1 - Installing Ansible And Ansible Navigator: modules/module-01-installing-ansible-and-ansible-navigator.md
  - Module 2 - Running Your First Playbook: modules/module-02-running-your-first-playbook.md
- Automation Manifest: automation-manifest.yaml
plugins:
- techdocs-core
